### ISSUE TITLE
Figure out CORS Policy Issues in Chrome

### ISSUE THREAD

**Issue by shanalily** [ZiniuYu/GoogleCardboardVR-AR#9]
The images in showPath.html show up in Firefox, but there are errors in Google Chrome, even after changing CORS settings in AWS. An example of the error I get in Chrome:
'Access to Image at 'https://s3.us-east-2.amazonaws.com/rpigooglecardboard/360Video2/48.jpg' from origin 'http://localhost:8000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8000' is therefore not allowed access.'

The CORS settings in AWS are currently set so they should allow the GET method from any origin.

Update: fixed some settings in S3 bucket, and added crossorigin="anonymous" to image tags, which mostly fixed the issue, but occasionally I still get the error, usually when I've just updated something.

**Comment by CorneliusHsiao** [comment]
The general solution is to obtain am key from S3 bucket by writing a function in any program that requests file accessing from AWS. Since this is hard to implement right now, I have set bucket, CORS configuration and other permission to public. Although it is not safe and everyone can read or write files, we keep it up to demo on Dec, 1 and may switch to RPI server in the future.
